version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    restart: unless-stopped
