version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - '80:80'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped
